import { Niche } from '../types/niche';

export const niches: Niche[] = [
  {
    id: "remodeling",
    title: "Bathroom & Kitchen Remodeling",
    niche_plural: "Kitchen & Bathroom Remodelers",
    revenue_potential: "$75K–$350K+",
    niche_business: "Remodeling",
    cheap_fix: "$500 handyman fix",
    premium_job: "$15K kitchen remodel",
    niche_work: "kitchen & bathroom remodels",
    niche_work_short: "remodeling work",
    niche_contractors: "remodeling contractors",
    niche_companies: "remodeling companies",
    customer_type_plural: "homeowners",
    customer_type_singular: "homeowner",
    pain_point_example: "outdated kitchen or bathroom",
    ad_headline_example: "\"Is your kitchen embarrassing you when guests come over?\" 😬",
    niche_estimate: "kitchen remodel estimate",
    sample_address: "123 Main St, Columbus OH",
    zip_1: "43026", zip_2: "43017", zip_3: "43235", zip_4: "43085", zip_5: "43016",
    roi_js_min: "5000", roi_js_max: "50000", roi_js_val: "15000", roi_js_step: "1000", roi_js_val_fmt: "15,000",
    adsImage: "/assets/Bathroom and Kitchen Remodeling.png"
  },
  {
    id: "water-fire-restoration",
    title: "Water & Fire Restoration",
    niche_plural: "Water & Fire Restoration Companies",
    revenue_potential: "$100K–$500K+",
    niche_business: "Restoration",
    cheap_fix: "minor leak cleanup",
    premium_job: "$20K water damage restoration",
    niche_work: "water & fire damage restorations",
    niche_work_short: "restoration work",
    niche_contractors: "restoration contractors",
    niche_companies: "restoration companies",
    customer_type_plural: "property owners",
    customer_type_singular: "property owner",
    pain_point_example: "flooded basement or smoke damage",
    ad_headline_example: "\"Dealing with unexpected water damage? We respond 24/7.\" 🚨",
    niche_estimate: "damage assessment",
    sample_address: "456 Oak Rd, Cleveland OH",
    zip_1: "44101", zip_2: "44113", zip_3: "44114", zip_4: "44115", zip_5: "44102",
    roi_js_min: "2000", roi_js_max: "100000", roi_js_val: "8000", roi_js_step: "1000", roi_js_val_fmt: "8,000",
    adsImage: "/assets/Water & Fire Restoration.png",
    ad_images: [
        "assets/water-ad-1.png",
        "assets/water-ad-2.png",
        "assets/water-ad-3.png",
        "assets/water-ad-4.png"
      ]
  },
  {
    id: "landscaping",
    title: "Landscaping",
    niche_plural: "Landscaping & Hardscaping Companies",
    revenue_potential: "$30K–$150K+",
    niche_business: "Landscaping",
    cheap_fix: "$100 lawn mow",
    premium_job: "$10K backyard oasis",
    niche_work: "landscaping & outdoor living spaces",
    niche_work_short: "landscaping work",
    niche_contractors: "landscaping contractors",
    niche_companies: "landscaping companies",
    customer_type_plural: "homeowners",
    customer_type_singular: "homeowner",
    pain_point_example: "overgrown yard or lack of curb appeal",
    ad_headline_example: "\"Want a backyard you can actually enjoy this summer?\" 🌳",
    niche_estimate: "landscaping quote",
    sample_address: "789 Pine Ln, Cincinnati OH",
    zip_1: "45202", zip_2: "45208", zip_3: "45209", zip_4: "45243", zip_5: "45226",
    roi_js_min: "1000", roi_js_max: "30000", roi_js_val: "5000", roi_js_step: "500", roi_js_val_fmt: "5,000",
    adsImage: "/assets/Landscaping.png"
  },
  {
    id: "fencing",
    title: "Fencing",
    niche_plural: "Fencing Contractors",
    revenue_potential: "$40K–$200K+",
    niche_business: "Fencing",
    cheap_fix: "$200 gate repair",
    premium_job: "$8K privacy fence installation",
    niche_work: "premium fence installations",
    niche_work_short: "fencing work",
    niche_contractors: "fencing contractors",
    niche_companies: "fencing companies",
    customer_type_plural: "homeowners",
    customer_type_singular: "homeowner",
    pain_point_example: "lack of privacy or an old, rotting fence",
    ad_headline_example: "\"Need more privacy in your backyard? Get a new fence installed fast.\" 🚧",
    niche_estimate: "fence measurement & quote",
    sample_address: "321 Cedar Ave, Dayton OH",
    zip_1: "45402", zip_2: "45409", zip_3: "45419", zip_4: "45429", zip_5: "45458",
    roi_js_min: "2000", roi_js_max: "20000", roi_js_val: "6000", roi_js_step: "500", roi_js_val_fmt: "6,000",
    adsImage: "/assets/Fencing.png"
  },
  {
    id: "masonry",
    title: "Masonry",
    niche_plural: "Masonry & Brickwork Specialists",
    revenue_potential: "$50K–$250K+",
    niche_business: "Masonry",
    cheap_fix: "$300 brick patch",
    premium_job: "$12K custom stone patio or retaining wall",
    niche_work: "custom brick & stone masonry",
    niche_work_short: "masonry work",
    niche_contractors: "masonry contractors",
    niche_companies: "masonry companies",
    customer_type_plural: "homeowners",
    customer_type_singular: "homeowner",
    pain_point_example: "crumbling steps or an ugly concrete patio",
    ad_headline_example: "\"Upgrade your home's curb appeal with beautiful custom stonework.\" 🧱",
    niche_estimate: "masonry estimate",
    sample_address: "654 Elm St, Akron OH",
    zip_1: "44303", zip_2: "44313", zip_3: "44333", zip_4: "44321", zip_5: "44308",
    roi_js_min: "3000", roi_js_max: "40000", roi_js_val: "10000", roi_js_step: "1000", roi_js_val_fmt: "10,000",
    adsImage: "/assets/Masonry.png"
  },
  {
    id: "concrete",
    title: "Concrete",
    niche_plural: "Concrete Contractors",
    revenue_potential: "$60K–$300K+",
    niche_business: "Concrete",
    cheap_fix: "$400 crack seal",
    premium_job: "$15K stamped concrete driveway",
    niche_work: "premium concrete pouring & flatwork",
    niche_work_short: "concrete work",
    niche_contractors: "concrete contractors",
    niche_companies: "concrete companies",
    customer_type_plural: "homeowners",
    customer_type_singular: "homeowner",
    pain_point_example: "cracked, sinking driveway",
    ad_headline_example: "\"Tired of looking at that cracked driveway? Get a beautiful new pour.\" 🚜",
    niche_estimate: "concrete quote",
    sample_address: "987 Maple Dr, Toledo OH",
    zip_1: "43604", zip_2: "43606", zip_3: "43614", zip_4: "43615", zip_5: "43617",
    roi_js_min: "2000", roi_js_max: "30000", roi_js_val: "8000", roi_js_step: "500", roi_js_val_fmt: "8,000",
    adsImage: "/assets/Concrete.png"
  }
];
